### ISSUE TITLE
Kinesis video signaling GetIceServerConfigCommand blocked by CORS policy

### ISSUE THREAD

**Issue by pdcarroll** [pdcarroll/react-kinesis-webrtc#3]
version 0.0.2

AWS SDK issue:
https://github.com/aws/aws-sdk-js-v3/issues/1962

**Comment by se0ga** [comment]
Hello @pdcarroll. 

Firstly, I want to thank you for your library, it looks fantastic.

I came across in the same issue and I want to ask is there any workaround for this problem?

Thank you.

**Comment by pdcarroll** [comment]
Hi, @se0ga. Thank you! 

I don't know of a workaround for AWS SDK v3. However, v2 of the AWS SDK (used in v0.0.1 of this library) does not have the issue.

**Comment by se0ga** [comment]
Thank you! Are there any major cons to use v2 of the AWS SDK?

**Comment by pdcarroll** [comment]
I think the biggest drawback to using v2 would be that it's a monolithic library with all of the services in the same package. Version 3 uses modular architecture, so you can install only the specific libraries you need (that was my biggest motivation factor in upgrading for this project).

**Comment by pdcarroll** [comment]
@se0ga This issue is resolved in version `3.6.0` of the aws sdk.
