### ISSUE TITLE
Use viewer without requesting camera or microphone permissions

### ISSUE THREAD

**Issue by orchydea** [pdcarroll/react-kinesis-webrtc#7]
Hi! Thanks for open sourcing this package!

I'm trying to build a visualization only tool. 

I'm using a master created with the [Kinesis WebRTC c SDK](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c) and I want to display the video on a webpage using this package without requesting the viewer's permission to use his microphone and/or camera, however, when using the [sample configuration for the viewer](https://github.com/pdcarroll/react-kinesis-webrtc#handle-a-media-stream-from-a-remote-master-peer) and setting both `video` and `audio` to false in the media configuration I get an error saying `TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': At least one of audio and video must be requested`. This prevents the viewer from displaying the video.

Is it possible to use the viewer without requesting any media devices from the host computer?

**Comment by pdcarroll** [comment]
@orchydea, thank you for creating this issue. This scenario should be possible using WebRTC, but I don't think it's supported in the current version of this library. I'll look into adding support for this and update this thread when I have more information.
