### ISSUE TITLE
Failed to execute 'addTrack' on 'RTCPeerConnection': A sender already exists for the track.

### ISSUE THREAD

**Issue by Maks-heso** [pdcarroll/react-kinesis-webrtc#8]
When I restart 4 times through the viewer to the master, an error appears Failed to execute 'addTrack' on 'RTCPeerConnection': A sender already exists for the track. How can this be fixed?

**Comment by pdcarroll** [comment]
@Maks-heso Thanks for the issue. I've seen this error intermittently before, and I believe it's a bug in this library. I'll plan to resolve this in the next release.
